FORMAT: 1A

# BCF-API
BCF-API is a service to exchange BCF-Topics

### Group Version
Version related resources of the **BCF-API**

### Schemas [/V0.99/schemas]
List all schemas

#### Link Schema [GET]
+ Response 200 (application/json)
         
            {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "description": "Link schema BCF REST API",
            "links": [
                {"rel": "topic", "href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/topic.json"},
                {"rel": "topic/bim_snippet","href": "href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/bim_snippet.json"},
                {"rel": "topic/document_references","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/document_references.json"},
                {"rel": "topic/related_topics","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/related_topics.json"},
                {"rel": "topic/comments","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/comments.json"},
                {"rel": "topic/viewpoints","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/viewpoints.json"},
                {"rel": "topic/visinfo","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/visinfo.json"},
                {"rel": "topic/components","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/components.json"}
                {"rel": "team","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/team.json"},
                {"rel": "team/project","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/project.json"},
                {"rel": "team/project/thumbnail","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/thumbnail.json"},
                {"rel": "team/project/discipline","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/discipline.json"},
                {"rel": "team/project/discipline/revision","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/revision.json"},
                {"rel": "team/project/discipline/revision/object","href": "https://raw.github.com/BuildingSMART/BCF-API/master/Schemas/object.json"}
                    ]
            }


### Schema [/V0.99/schemas/{rel}]
A single schema

+ Parameters
    + rel (required, string, `topic`) ... `relation` of the schema.

    
#### Retrieve schema [GET]
+ Response 200 (application/json)
            
     + Body
         
            {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "description": "Schema for Topic BCF REST API",
            "type": "object",
            "definitions": {
            "guid": {
            "type": "string",
            "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"}
            },
            "properties": {
            "reference_link": {"type": "string"},
            "title": {"type": "string"},
            "index": {"type": "integer","minimum": 0},
            "label": {"$ref": "extensions.json#/definitions/topic_label"},
            "creation_date": {"type": "string","format": "date-time"},
            "modified_date": {"type": "string","format": "date-time"},
            "assigned_to": {"$ref": "extensions.json#/definitions/user_id_type"},
            "guid": {"$ref": "#/definitions/guid"},"topic_type": {
            "$ref": "extensions.json#/definitions/topic_type"},
            "topic_status": {"$ref": "extensions.json#/definitions/topic_status"}
            },
            "required": ["title","guid"],
            "links": [
                {"rel": "document_references","href": "{guid}/document_references"},
                {"rel": "bim_snippet","href": "{guid}/bim_snippet"},
                {"rel": "related_topics","href": "{guid}/related_topics"},
                {"rel": "comments","href": "{guid}/comments"}
                    ]
            }



### Group Authentication
Authentication related resources of the **BCF-API**

### Group User
User Rights and Roles related resources of the **BCF-API**

### Group Team
Team related resources of the **BCF-API**

### Group Project
Project related resources of the **BCF-API**

### Group Discipline
Descipline related resources of the **BCF-API**

### Group Revision
Revision related resources of the **BCF-API**

### Group Object
Object related resources of the **BCF-API**

### Group Topics
Topics related resources of the **BCF-API**

### Topics [/V0.99/teams/{id}/projects/{id}/topics]
#### List all Topics [GET]
+ Response 200 (application/json)


        [
            {
            "guid": "bbe8a313-d576-4c8e-b88d-065988bc855a",
            "title": "Wrong Window",
            "label": "Specfications"
             },
             {
           "guid": "ab770b4f-b590-4056-83a6-683c5e226a7d",
            "title": "PfV Architecture/Heating"
            "label": "Architecture"
            }
        ]
        
### Topic [/V0.99/teams/{id}/projects/{id}/topics/{guid}]
A single Topic object with all its details

+ Parameters
    + guid (required, string, `ab770b4f-b590-4056-83a6-683c5e226a7d`) ... `guid` of the Topic.
    
#### Retrieve a Topic [GET]
+ Response 200 (application/json)
            
     + Body
         
            {
            "reference_link": "http://www.buildingmart....",
            "title": "PfV Architecture/Heating",
            "index": 1,
            "label": "Architecture",
            "creation_date": "2012-04-23T18:25:43.511Z",
            "modified_date": "2012-04-23T18:25:43.511Z",
            "assigned_to": "karl@mustermann.de",
            "guid": "ab770b4f-b590-4056-83a6-683c5e226a7d",
            "topic_type": "Request",
            "topic_status": "Open"
            }

### Comments [/V0.99/teams/{id}/projects/{id}/topics/{guid}/comments]
All Comments related to a topic

+ Parameters
    + guid (required, string, `ab770b4f-b590-4056-83a6-683c5e226a7d`) ... `guid` of the Topic.
    
#### Retrieve all Comments related to a Topic [GET]
+ Response 200 (application/json)
            
    + Body
    
            [
            {
            "guid": "ca440b4f-b110-4056-83d6-338c5e226a4a",
            "verbalstatus": "Open",
            "status": "unknown",
            "date": "2012-04-23T18:25:44.511Z",
            "author": "fritz@domain1.com",
            "comment": "this is a comment",
            "topic": {
            "guid": "ab770b4f-b590-4056-83a6-683c5e226a7d"
            },
            "modifieddate": "2012-04-23T18:25:44.511Z",
            "priority": "2"
            },
            {
            "guid": "dd550b4f-b110-4056-83d6-337c5e226a22",
            "verbalstatus": "In Progress",
            "status": "unknown",
            "date": "2012-04-23T18:25:44.511Z",
            "author": "karl@mustermann.de",
            "comment": "this is the answer to a comment",
            "topic": {
            "guid": "ab770b4f-b590-4056-83a6-683c5e226a7d"
            },
            "modifieddate": "2012-05-14T17:22:44.511Z",
            "priority": "2"
            }
            ]

### Create a Comment [POST]
+ Request (application/json)

            {
            "guid": "dd550b4f-b110-4056-83d6-337c5e226a22",
            "verbalstatus": "In Progress",
            "status": "unknown",
            "date": "2012-04-23T18:25:44.511Z",
            "author": "karl@mustermann.de",
            "comment": "this is the answer to a comment",
            "topic": {
            "guid": "ab770b4f-b590-4056-83a6-683c5e226a7d"
            },
            "modifieddate": "2012-05-14T17:22:44.511Z",
            "priority": "2"
            }

+ Response 201 (application/json)

        { "guid": "dd550b4f-b110-4056-83d6-337c5e226a22", 
          "comment": "this is the answer to a comment",
          "topic": 
          {"guid": "ab770b4f-b590-4056-83a6-683c5e226a7d"}
        }
        