FORMAT: 1A

# BCF-API
BCF-API is a service to exchange BCF-Topics
# Group Topics
Topics related resources of the **BCF-API**

## Topics Collection [/topics]
### List all Topics [GET]
+ Response 200 (application/json)

        [{
          "guid": "bbe8a313-d576-4c8e-b88d-065988bc855a", "title": "Wrong Window"
        }, {
          "guid": "ab770b4f-b590-4056-83a6-683c5e226a7d", "title": "Clash Architecture/Heating"
        }]

